# Generated by Django 5.1.2 on 2024-10-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('domain', models.CharField(max_length=100)),
                ('tech', models.CharField(max_length=100)),
                ('stack', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=50)),
            ],
        ),
    ]
